server:
  port: 8080

spring:
  application:
    name: seller-service

  kafka:
    bootstrap-servers: kafka:9092

  datasource:
    url: jdbc:postgresql.Driver://seller-db:5432/seller
    username: postgres
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

